import assert from 'node:assert/strict';
import { assign, available, displayed, emptySlots, evaluateBrief, evaluateFinale, feasible, finaleTarget, offeredBriefs, reconcile, redeemAffectedPlinth } from '../games/museum-of-almost-nothing/rules.ts';

const threePebbles = [3n, 0n, 0n, 0n];
let slots = emptySlots();
slots = assign(threePebbles, slots, 0, 1);
slots = assign(threePebbles, slots, 1, 1);
slots = assign(threePebbles, slots, 2, 1);
assert.deepEqual(slots, [1, 1, 1], 'three aggregate copies can fill three plinths');
assert.equal(displayed(slots, 1), 3n);
assert.equal(available(threePebbles, slots, 1), 0n);
assert.equal(assign(threePebbles, slots, 2, 1), slots, 'same-slot placement is a no-op');
assert.deepEqual(assign([2n, 0n, 0n, 0n], [1, 1, null], 2, 1), [1, 1, null], 'cannot allocate a third copy when only two are owned');
assert.deepEqual(reconcile([2n, 0n, 0n, 0n], slots), [1, 1, null], 'redeeming all-displayed stock clears highest numbered matching plinth');
assert.deepEqual(reconcile([0n, 0n, 0n, 0n], [1, null, null]), [null, null, null], 'last owned copy clears display');
assert.equal(redeemAffectedPlinth([4n, 0n, 0n, 0n], slots, 1), null, 'undisplayed stock is redeemed first');
assert.equal(redeemAffectedPlinth(threePebbles, slots, 1), 3);
slots = assign(threePebbles, slots, 1, null);
assert.deepEqual(slots, [1, null, 1], 'remove returns one available allocation');
assert.equal(available(threePebbles, slots, 1), 1n);
slots = assign([3n, 1n, 0n, 0n], slots, 2, 2);
assert.deepEqual(slots, [1, null, 2], 'replacement returns old allocation');
assert.equal(available([3n, 1n, 0n, 0n], slots, 1), 2n);

assert.deepEqual(offeredBriefs([1n, 0n, 0n, 0n], 0), ['opening']);
assert.deepEqual(offeredBriefs([1n, 0n, 0n, 0n], 1), ['opening']);
assert.deepEqual(offeredBriefs([2n, 0n, 0n, 0n], 1), ['resemblance']);
assert.deepEqual(offeredBriefs([1n, 1n, 0n, 0n], 1), ['different']);
assert.deepEqual(offeredBriefs([2n, 1n, 0n, 0n], 1), ['resemblance', 'different']);
assert.equal(feasible([1n, 0n, 0n, 0n], 'resemblance'), false);
assert.equal(evaluateBrief('opening', [null, 1, null], [2]), null);
assert.match(evaluateBrief('opening', [1, 1, null], [1, 2]), /exactly one/);
assert.equal(evaluateBrief('resemblance', [1, null, 1], [1, 3]), null);
assert.match(evaluateBrief('resemblance', [1, null, 1], [3, 1]), /left occupied/);
assert.equal(evaluateBrief('different', [1, null, 2], [1, 3]), null);
assert.match(evaluateBrief('different', [1, null, 1], [1, 3]), /different/);
assert.match(evaluateBrief('different', [1, null, 2], [1, 1]), /exactly once/);

assert.equal(finaleTarget([1n, 0n, 0n, 0n]), 1);
assert.equal(finaleTarget([2n, 0n, 0n, 0n]), 2);
assert.equal(finaleTarget(threePebbles), 3);
assert.equal(evaluateFinale([1n, 0n, 0n, 0n], [null, 1, null], [2]), null);
assert.match(evaluateFinale([1n, 0n, 0n, 0n], [1, null, null], [1]), /center/);
assert.equal(evaluateFinale([2n, 0n, 0n, 0n], [1, null, 1], [1, 3]), null);
assert.equal(evaluateFinale([1n, 1n, 0n, 0n], [1, null, 2], [1, 3]), null);
assert.equal(evaluateFinale(threePebbles, [1, 1, 1], [1, 3, 2]), null);
assert.equal(evaluateFinale([1n, 1n, 1n, 0n], [1, 2, 3], [3, 1, 2]), null);
assert.match(evaluateFinale(threePebbles, [1, 1, 1], [1, 2, 3]), /center/);
assert.match(evaluateFinale([0n, 0n, 0n, 0n], emptySlots(), []), /Nothing remained/);
console.log('PASS museum rules: aggregate allocation, duplicate/redeem reconciliation, feasibility/order, adaptive finale.');
